apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::966656825171:role/eksctl-eksctl-demo-nodegroup-ng-5-NodeInstanceRole-CPMS11DQRFM6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::966656825171:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-07T08:04:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4881"
  uid: 6c19a0cb-b186-411d-b551-de38d4bf7b3c
